algo: ppo
envparameters:
  action_continuous: false
  action_space: 7
  n_player: 1
  obs_continuous: true
  obs_space: [7,7,3]
  scenario: MiniGrid-Empty-5x5-v0
hyperparameters:
  cnn:
    use_cnn_encoder: true
    input_chanel: 3
    channel_list: [32,32]
    kernel_list: [4,2]
    stride_list: [1,2]
  a_lr: 0.0005
  batch_size: 256
  buffer_capacity: 1024
  c_lr: 0.0005
  clip_param: 0.2
  epsilon: 0
  epsilon_end: 0
  gamma: 0.99
  hidden_size: 128
  num_hidden_layer: 2
  learn_terminal: true
  marl: false
  max_grad_norm: 0.5
  update_freq: 1
  use_network: true
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 50
  max_episodes: 10000
  render: false
  save_interval: 100
  use_cuda: true
