algo: ac
envparameters:
  action_continuous: false
  action_space: 3
  n_player: 1
  obs_continuous: true
  obs_space: 6
  scenario: classic_Acrobot-v1
hyperparameters:
  batch_size: 64
  buffer_capacity: 1024
  c_lr: 0.001
  gamma: 0.99
  hidden_size: 64
  num_hidden_layer: 1
  learn_terminal: true
  marl: false
  use_network: true
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 20
  max_episodes: 1000
  render: false
  save_interval: 100
  use_cuda: false
