algo: ddpg
envparameters:
  action_continuous: true
  action_space: 1
  n_player: 1
  obs_continuous: true
  obs_space: 3
  scenario: classic_Pendulum-v0
hyperparameters:
  a_lr: 0.001
  batch_size: 64
  buffer_capacity: 1024
  c_lr: 0.0005
  continuous_action_max: 2
  continuous_action_min: -2
  epsilon: 0.5
  epsilon_end: 0.01
  gamma: 0.99
  hidden_size: 100
  learn_freq: 1
  learn_terminal: false
  marl: false
  num_hidden_layer: 1
  policy_type: continuous
  tau: 0.001
  update_freq: 1
  use_network: true
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 20
  max_episodes: 1000
  render: false
  save_interval: 100
  use_cuda: false
