algo: dqn
envparameters:
  action_continuous: false
  action_space: 7
  n_player: 1
  obs_continuous: true
  obs_space: [7,7,3]
  scenario: MiniGrid-DoorKey-5x5-v0
hyperparameters:
  cnn:
    use_cnn_encoder: true
    input_chanel: 3
    channel_list: [32,32]
    kernel_list: [4,2]
    stride_list: [1,2]
  batch_size: 256
  buffer_capacity: 10240
  c_lr: 0.0005
  epsilon: 0.9
  epsilon_end: 0.2
  gamma: 0.99
  hidden_size: 128
  num_hidden_layer: 1
  marl: false
  target_replace: 50
  use_network: true
  max_grad_norm: 0.1
  update_freq: 1
  pretrain:
    encoder_path:
    actor_path:
    critic_path:
seedparameters:
  seed_nn: 1
  seed_np: 1
  seed_random: 1
trainingparameters:
  evaluate_rate: 100
  learn_freq: 1
  learn_terminal: false
  max_episodes: 10000
  render: false
  save_interval: 500
  use_cuda: true
